#!/bin/bash
 wget "https://brianmechanisms.github.io/meshes/meshes/botarmbots/24-006/3 point beige.hdr"
 wget "https://brianmechanisms.github.io/meshes/meshes/botarmbots/24-006/joint1Pin.mtl"
 wget "https://brianmechanisms.github.io/meshes/meshes/botarmbots/24-006/joint1Pin.obj"
 wget "https://brianmechanisms.github.io/meshes/meshes/botarmbots/24-006/joint1Plate.mtl"
 wget "https://brianmechanisms.github.io/meshes/meshes/botarmbots/24-006/joint1Plate.obj"
 wget "https://brianmechanisms.github.io/meshes/meshes/botarmbots/24-006/joint1PlateWheel.mtl"
 wget "https://brianmechanisms.github.io/meshes/meshes/botarmbots/24-006/joint1PlateWheel.obj"
 wget "https://brianmechanisms.github.io/meshes/meshes/botarmbots/24-006/joint2Plate.mtl"
 wget "https://brianmechanisms.github.io/meshes/meshes/botarmbots/24-006/joint2Plate.obj"
 wget "https://brianmechanisms.github.io/meshes/meshes/botarmbots/24-006/lowerArm.mtl"
 wget "https://brianmechanisms.github.io/meshes/meshes/botarmbots/24-006/lowerArm.obj"
 wget "https://brianmechanisms.github.io/meshes/meshes/botarmbots/24-006/softbox.png"
 wget "https://brianmechanisms.github.io/meshes/meshes/botarmbots/24-006/torso.mtl"
 wget "https://brianmechanisms.github.io/meshes/meshes/botarmbots/24-006/torso.obj"
 wget "https://brianmechanisms.github.io/meshes/meshes/botarmbots/24-006/upperArmLink.mtl"
 wget "https://brianmechanisms.github.io/meshes/meshes/botarmbots/24-006/upperArmLink.obj"
