#!/bin/bash
 wget "https://brianmechanisms.github.io/meshes/meshes/botarmbots/24-007/3 point beige.hdr"
 wget "https://brianmechanisms.github.io/meshes/meshes/botarmbots/24-007/ULMW-24-007-concept.mtl"
 wget "https://brianmechanisms.github.io/meshes/meshes/botarmbots/24-007/ULMW-24-007-concept.obj"
 wget "https://brianmechanisms.github.io/meshes/meshes/botarmbots/24-007/hood-24-007-concept.mtl"
 wget "https://brianmechanisms.github.io/meshes/meshes/botarmbots/24-007/hood-24-007-concept.obj"
 wget "https://brianmechanisms.github.io/meshes/meshes/botarmbots/24-007/innerLegBottom-24-007-concept.mtl"
 wget "https://brianmechanisms.github.io/meshes/meshes/botarmbots/24-007/innerLegBottom-24-007-concept.obj"
 wget "https://brianmechanisms.github.io/meshes/meshes/botarmbots/24-007/innerLegTop-24-007-concept.mtl"
 wget "https://brianmechanisms.github.io/meshes/meshes/botarmbots/24-007/innerLegTop-24-007-concept.obj"
 wget "https://brianmechanisms.github.io/meshes/meshes/botarmbots/24-007/outerLeg-24-007-concept.mtl"
 wget "https://brianmechanisms.github.io/meshes/meshes/botarmbots/24-007/outerLeg-24-007-concept.obj"
 wget "https://brianmechanisms.github.io/meshes/meshes/botarmbots/24-007/softbox.png"
